classDiagram
    ScooterApp "1" <--> "*"Scooter
    ScooterApp "1" <--> "*" User
    Scooter "1" <--> "1" User
class Scooter {
    -Obj Station
    -Obj User
    -int Serial
    -int Charge
    -bool IsBroken
    -bool IsDocked
    +Rent()
    +Dock(Station)
    +Recharge()
    +RequestRepair()
}

class User {
    -str Username
    -str Password
    -int Age
}

class ScooterApp {
    -Array Obj Stations
    -Array Users
    -Array Obj Sessions
    +Register(User)
    +Login(Username, Password)
    +AddScooter(Location)
    +RemoveScooter(Scooter Obj)
}
