sequenceDiagram
    actor Customer
    Customer ->> App: Log in
    activate App
    App ->> Add Scooter: Added Scooter
    activate Add Scooter
    Add Scooter ->> Remove Scooter: Added
    deactivate Add Scooter
    activate Remove Scooter
    Add Scooter --> Remove Scooter: Display calculate total
    deactivate Remove Scooter

    alt cancels custom items
        Customer ->> Basket: Cancel
        Basket ->> customItem: Remove
        deactivate customItem
        Basket -->> Customer: Confirm Cancelation
    else adds to total purchase
        activate customItem
        Customer ->> Basket: Display calculate total
        activate Basket
        Basket -->> Customer: Confirm
    end

    alt cancels purchase
        Customer ->> Basket: Cancel
        Basket ->> Car: Remove
        deactivate Car
        Basket -->> Customer: Confirm Cancelation
    else completes purchase
        activate Car
        Customer ->> Basket: Payment details
        activate Basket
        Basket -->> Customer: Confirm
        deactivate Basket
        Car ->> Customer: Ship
        deactivate Car
    end
