sequenceDiagram
    actor Customer
    Customer ->> Log in: Log in
    activate Log in
    Log in ->> Add Scooter: Added Scooter
    activate Add Scooter
    Add Scooter ->> Remove Scooter: Remove Scooter
    deactivate Add Scooter
    activate Remove Scooter
    Remove Scooter --> Log out: Log out
    deactivate Remove Scooter

    alt register user
        Customer ->> Log in: register user
        Log in ->> User name: Add user name
        Log in ->>  User password: Add user password
        Log in ->>  User age: Add user age
        Log in -->> Confirm: Confirm Registration
        activate Login
    else Already a user 
        Log in ->> User name: Already a user
        Log in ->>  User password: Add user password
        Log in -->> New user name: Enter new User name or password
x
    end

    